version: '3.8'

services:
  recipe-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_CLUSTER}/recipedb?retryWrites=true&w=majority
      - JWT_SECRET=RecipeSecretKey123456789012345678901234567890
      - JWT_EXPIRATION=86400
    restart: always

  recipe-web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - recipe-api